### ISSUE TITLE
GT Editor?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#97]
I'm currently getting the following error (dev console) when I build GT projects from the test workspace:

```
java.lang.NullPointerException
	at org.emoflon.ibex.common.utils.IBeXPatternUtils.lambda$0(IBeXPatternUtils.java:26)
	at org.emoflon.ibex.common.utils.IBeXPatternUtils$$Lambda$635/1255435395.compare(Unknown Source)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at org.emoflon.ibex.gt.transformations.EditorToIBeXPatternTransformation.createSortedPatternSet(EditorToIBeXPatternTransformation.java:78)
	at org.emoflon.ibex.gt.transformations.Editor
...
```

**Comment by patrickrobrecht** [comment]
I cannot reproduce this error in my test workspace. All GT projects from TestsuiteGT and de.upb.mbse.taxcalculationexample.businessrules build without any errors (using master branch of all repositories). How exactly do I reproduce this issue?

Note that is not an editor bug anyway as the transformation is in [emoflon-ibex](https://github.com/eMoflon/emoflon-ibex).

**Comment by anthonyanjorin** [comment]
I get the error as a print out in my dev console (while running the test workspace in a runtime eclipse instance).  I guess it’s just robustness as everything works (no visible errors in the runtime workspace).
If you can’t reproduce I’ll try to fix it myself.
